In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import gmaps.datasets
import requests
# Import the API key.
from config import g_key

In [2]:
#pull in g-key
gmaps.configure(api_key=g_key)

gmaps.configure(api_key=g_key)

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Westport,US,2020-04-18 19:42:22,41.14,-73.36,44.60,70,90,14.99,overcast clouds,0.00,0.0
1,1,Omboue,GA,2020-04-18 19:42:23,-1.57,9.26,79.72,89,96,5.73,light rain,0.34,0.0
2,2,Margate,GB,2020-04-18 19:40:16,51.38,1.39,48.99,91,35,14.70,scattered clouds,0.00,0.0
3,3,Kapaa,US,2020-04-18 19:42:23,22.08,-159.32,78.80,65,1,11.41,clear sky,0.00,0.0
4,4,Duluth,US,2020-04-18 19:37:56,46.78,-92.11,55.40,35,75,11.41,broken clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,551,Launceston,AU,2020-04-18 19:40:41,-41.45,147.17,39.99,80,65,3.36,broken clouds,0.00,0.0
552,552,San Lawrenz,MT,2020-04-18 19:44:30,36.06,14.20,63.00,93,88,3.36,overcast clouds,0.00,0.0
553,553,Mitu,CO,2020-04-18 19:44:30,1.20,-70.17,75.42,81,99,4.12,light rain,0.14,0.0
554,554,Rajgarh,IN,2020-04-18 19:44:30,28.63,75.38,79.57,35,74,4.81,broken clouds,0.00,0.0
555,555,Mizdah,LY,2020-04-18 19:40:46,31.45,12.98,70.41,26,0,14.50,clear sky,0.00,0.0

In [4]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
raining = str(input("Do you want it to be raining? (yes/no) "))
snowing = str(input("Do you want it to be snowing (yes/no)? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 80
Do you want it to be raining? (yes/no) no
Do you want it to be snowing (yes/no)? no

In [5]:
# Filter the dataset to find the cities that fit the criteria (and ifs for rain and snow)
if raining == 'yes' and snowing == 'yes':
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & (city_data_df["Rain inches (last 3 hrs)"] > 0) & (city_data_df["Snow inches (last 3 hrs)"] > 0)]
elif raining =='no' and snowing == 'yes': 
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & (city_data_df["Rain inches (last 3 hrs)"] == 0) & (city_data_df["Snow inches (last 3 hrs)"] > 0)]
elif raining =='yes' and snowing == 'no': 
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & (city_data_df["Rain inches (last 3 hrs)"] > 0) & (city_data_df["Snow inches (last 3 hrs)"] == 0)]    
elif raining =='no' and snowing == 'no': 
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & (city_data_df["Rain inches (last 3 hrs)"] == 0) & (city_data_df["Snow inches (last 3 hrs)"] == 0)]    
else:
    print("Please enter a number for min and max temps and yes/no for rain/snow")
    
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
3,3,Kapaa,US,2020-04-18 19:42:23,22.08,-159.32,78.80,65,1,11.41,clear sky,0.0,0.0
5,5,Rikitea,PF,2020-04-18 19:42:24,-23.12,-134.97,77.11,70,26,6.31,scattered clouds,0.0,0.0
6,6,Port Elizabeth,ZA,2020-04-18 19:42:24,-33.92,25.57,66.20,93,0,4.70,clear sky,0.0,0.0
8,8,Atar,MR,2020-04-18 19:42:25,20.52,-13.05,74.34,19,0,8.01,clear sky,0.0,0.0
9,9,East London,ZA,2020-04-18 19:42:25,-33.02,27.91,71.13,65,0,17.90,clear sky,0.0,0.0
13,13,Sai Buri,TH,2020-04-18 19:42:26,6.70,101.62,79.86,83,100,6.17,overcast clouds,0.0,0.0
15,15,Cockburn Town,TC,2020-04-18 19:38:33,21.46,-71.14,79.09,78,77,13.40,broken clouds,0.0,0.0
17,17,Saint-Philippe,RE,2020-04-18 19:42:27,-21.36,55.77,77.00,78,20,17.22,few clouds,0.0,0.0
19,19,Ponta Do Sol,PT,2020-04-18 19:42:27,32.67,-17.10,61.00,58,11,13.00,few clouds,0.0,0.0
20,20,Coquimbo,CL,2020-04-18 19:42:27,-29.95,-71.34,64.40,72,40,10.29,scattered clouds,0.0,0.0

In [6]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp","Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Kapaa,US,78.80,clear sky,22.08,-159.32,
5,Rikitea,PF,77.11,scattered clouds,-23.12,-134.97,
6,Port Elizabeth,ZA,66.20,clear sky,-33.92,25.57,
8,Atar,MR,74.34,clear sky,20.52,-13.05,
9,East London,ZA,71.13,clear sky,-33.02,27.91,
13,Sai Buri,TH,79.86,overcast clouds,6.70,101.62,
15,Cockburn Town,TC,79.09,broken clouds,21.46,-71.14,
17,Saint-Philippe,RE,77.00,few clouds,-21.36,55.77,
19,Ponta Do Sol,PT,61.00,few clouds,32.67,-17.10,
20,Coquimbo,CL,64.40,scattered clouds,-29.95,-71.34,

In [7]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [8]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Kapaa,US,78.80,clear sky,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
5,Rikitea,PF,77.11,scattered clouds,-23.12,-134.97,Pension Maro'i
6,Port Elizabeth,ZA,66.20,clear sky,-33.92,25.57,39 On Nile Guest House
8,Atar,MR,74.34,clear sky,20.52,-13.05,Oumou Elghoura
9,East London,ZA,71.13,clear sky,-33.02,27.91,Tu Casa
13,Sai Buri,TH,79.86,overcast clouds,6.70,101.62,หอพักนักเรียนหญิงโรงเรียนสายบุรีอิสลามวิทยา
15,Cockburn Town,TC,79.09,broken clouds,21.46,-71.14,Osprey Beach Hotel
17,Saint-Philippe,RE,77.00,few clouds,-21.36,55.77,"Chambres d'hôte ""La Trinité"""
19,Ponta Do Sol,PT,61.00,few clouds,32.67,-17.10,Hotel do Campo
20,Coquimbo,CL,64.40,scattered clouds,-29.95,-71.34,Hotel San Juan

In [9]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

In [10]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [11]:
# Add a pop-up marker for each desired city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"
# Export the hotel_data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")